"""In the client table, change the type of the role_id attribute UUID to INT. I did the same in the table

Revision ID: 05f1b2814ba0
Revises: 7ea0e55245dd
Create Date: 2025-06-16 12:07:14.598588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f1b2814ba0'
down_revision: Union[str, None] = '7ea0e55245dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('role', recreate='always') as batch_op:
        batch_op.alter_column('id',
                existing_type=sa.CHAR(length=32),
                type_=sa.Integer(),
                existing_nullable=False)
        
    with op.batch_alter_table('client', recreate='always') as batch_op:
        batch_op.alter_column('role_id',
                existing_type=sa.CHAR(length=32),
                type_=sa.Integer(),
                existing_nullable=False)
        
    with op.batch_alter_table('product') as batch_op:
        batch_op.alter_column(
            'is_active',
            existing_type=sa.BOOLEAN(),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.create_table('_alembic_tmp_client',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_client_email')),
    sa.UniqueConstraint('username', name=op.f('uq_client_username'))
    )
    # ### end Alembic commands ###
