"""add is active in product

Revision ID: 18f985c2f5b6
Revises: 79e905584e7a
Create Date: 2025-06-13 12:44:11.450425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f985c2f5b6'
down_revision: Union[str, None] = '79e905584e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_client_password'), 'client', type_='unique')
    with op.batch_alter_table('product') as batch_op:
     batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_active')
    op.create_unique_constraint(op.f('uq_client_password'), 'client', ['password'])
    # ### end Alembic commands ###
