"""add unique parameters to entities

Revision ID: 79e905584e7a
Revises: 0d0b2cac1a4d
Create Date: 2025-06-12 17:18:28.572068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e905584e7a'
down_revision: Union[str, None] = '0d0b2cac1a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table('category') as batch_op:
     batch_op.create_unique_constraint('uq_category_name', ['name'])

    with op.batch_alter_table('client') as batch_op:
     batch_op.create_unique_constraint('uq_client_username', ['username'])
     batch_op.create_unique_constraint('uq_client_password', ['password'])
     batch_op.create_unique_constraint('uq_client_email', ['email'])

    with op.batch_alter_table('employee') as batch_op:
     batch_op.create_unique_constraint('uq_employee_username', ['username'])
     batch_op.create_unique_constraint('uq_employee_password', ['password'])
     batch_op.create_unique_constraint('uq_employee_email', ['email'])

    with op.batch_alter_table('product') as batch_op:
     batch_op.create_unique_constraint('uq_product_name', ['name'])

    with op.batch_alter_table('role') as batch_op:
     batch_op.create_unique_constraint('uq_role_name', ['name'])




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
