"""add enum in status attribute in order

Revision ID: 7ea0e55245dd
Revises: 97b6e8583104
Create Date: 2025-06-15 19:48:11.536688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea0e55245dd'
down_revision: Union[str, None] = '97b6e8583104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('order', recreate='always') as batch_op:
        batch_op.alter_column('status',
                existing_type=sa.String(),
                type_=sa.Enum('PAID', 'PENDING', 'CANCELED', name='statusorderenum'),
                existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
