"""add is active in entity category and employee

Revision ID: 97b6e8583104
Revises: 18f985c2f5b6
Create Date: 2025-06-14 18:06:59.361549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b6e8583104'
down_revision: Union[str, None] = '18f985c2f5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', recreate='always') as batch_op:
        batch_op.alter_column('is_active', 
                existing_type=sa.BOOLEAN(),
                nullable=False,
                existing_server_default=sa.text('1'))

    with op.batch_alter_table('order', recreate='always') as batch_op:
        batch_op.alter_column('status',
                existing_type=sa.String(),
                type_=sa.Enum('PAID', 'PENDING', 'CANCELED', name='statusorderenum'),
                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('employee', 'is_active')
    op.create_unique_constraint(op.f('uq_client_password'), 'client', ['password'])
    # ### end Alembic commands ###
